## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  # - nightly

codecov: true
coveralls: true

notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
 apt: # apt-get for linux
   packages:
   - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("TrajectoryOptimization"); Pkg.test("TrajectoryOptimization"; coverage=true)'
# after_success:
#   # push coverage results to Coveralls
#   - julia -e 'cd(Pkg.dir("TrajectoryOptimization")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#   # push coverage results to Codecov
#   - julia -e 'cd(Pkg.dir("TrajectoryOptimization")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'


# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.1
#       os: linux
#       script:
#           - julia --project=docs -e 'using Pkg; Pkg.instantiate()'
#           - julia --project=docs --color=yes -e 'timer = Timer(timer -> @info("Still running"), 60; interval=60); include("docs/make.jl"); close(timer);'
#       after_success: skip
